server:
  port: 8004
spring:
  application:
    name: consumer   #服务名称，随意取

  rabbitmq:
    host: localhost
    port: 7000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka #注册到Eureka的地址

management:
  endpoints:
    web:
      exposure:
        include: "*"